# Generated by Django 2.2.6 on 2020-06-17 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_paint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paint',
            options={'ordering': ['order']},
        ),
    ]
