# Generated by Django 2.2.6 on 2020-06-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_auto_20200617_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='pic',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
