# Generated by Django 2.2.6 on 2020-06-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_auto_20200618_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='paint',
            name='image',
            field=models.ImageField(default=0, upload_to='static/img'),
        ),
    ]
