# Generated by Django 2.2.6 on 2020-07-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pic',
            field=models.ImageField(max_length=225, upload_to=''),
        ),
    ]
