# Generated by Django 2.2.6 on 2020-07-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200710_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pic',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
