# Generated by Django 2.2.6 on 2020-07-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200710_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pic',
            field=models.ImageField(upload_to='static/img/order'),
        ),
    ]
