# Generated by Django 2.2.6 on 2020-07-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200712_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(help_text='Contact phone number', max_length=13),
        ),
    ]
