# Generated by Django 2.2.6 on 2020-07-18 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20200717_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(regex='^\\+[0-9]{12}$')]),
        ),
    ]
